# Generated by Django 5.1.4 on 2026-06-06 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolYear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolYear.schoolyear')),
            ],
        ),
    ]
