# Generated by Django 6.0.6 on 2026-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='is_active',
        ),
        migrations.AddField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Current Term'),
        ),
    ]
