# Generated by Django 6.0.6 on 2026-06-08 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0002_remove_term_is_active_term_is_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='is_current',
        ),
    ]
