# Generated by Django 6.0.6 on 2026-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0003_remove_term_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Current Term'),
        ),
    ]
