# Generated by Django 6.0.6 on 2026-06-12 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('sections', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('component', models.CharField(blank=True, choices=[('WW', 'Written Works'), ('PT', 'Performance Tasks'), ('TE', 'Term Exam')], null=True)),
                ('activity_type', models.CharField(choices=[('graded', 'Graded Activity'), ('compliance', 'Compliance Check'), ('recorded', 'Recorded Only')], default='graded')),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_complied', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.activity')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
            ],
            options={
                'unique_together': {('activity', 'enrollment')},
            },
        ),
    ]
