# Generated by Django 6.0.6 on 2026-06-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('component', models.CharField(blank=True, choices=[('WW', 'Written Works'), ('PT', 'Performance Tasks'), ('TE', 'Term Exam')], null=True)),
                ('activity_type', models.CharField(choices=[('graded', 'Graded Activity'), ('compliance', 'Compliance Check'), ('recorded', 'Recorded Only')], default='graded')),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_complied', models.BooleanField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
