# Generated by Django 6.0.6 on 2026-06-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_graded',
        ),
        migrations.AlterField(
            model_name='activity',
            name='component',
            field=models.CharField(blank=True, choices=[('WW', 'Written Works'), ('PT', 'Performance Tasks'), ('TE', 'Term Exam')], null=True),
        ),
    ]
