# Generated by Django 6.0.6 on 2026-06-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_initial'),
        ('scores', '0002_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
        migrations.AddField(
            model_name='score',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.activity'),
        ),
        migrations.AddField(
            model_name='score',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('activity', 'enrollment')},
        ),
    ]
