# Generated by Django 6.0.6 on 2026-06-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_seen_guide',
            field=models.BooleanField(default=False),
        ),
    ]
