# Generated by Django 5.1.4 on 2026-06-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birth_cert',
            field=models.CharField(choices=[('Y', 'With Birth Certificate'), ('N', 'No Birth Certificate')], default='Y', max_length=5),
        ),
    ]
