# Generated by Django 6.0.6 on 2026-06-10 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolYear', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('grade_level', models.IntegerField(null=True)),
                ('class_type', models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], default='JHS', max_length=100, null=True)),
                ('is_adviser', models.BooleanField(default=True)),
                ('is_subject_teacher', models.BooleanField(default=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_id', models.CharField(max_length=50)),
                ('principal_name', models.CharField(max_length=100, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(default='S.Y. 2026-2027', limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='schoolYear.schoolyear')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('academic_elective', 'Academic Elective - All Other'), ('academic_field', 'Academic Elective - Field/Exposure/Sports/Arts'), ('techpro_elective', 'TechPro Elective - All Other'), ('techpro_immersion', 'TechPro Elective - Work Immersion')], default='core', max_length=20)),
                ('order', models.IntegerField()),
                ('is_handled_by_owner', models.BooleanField(default=False, help_text='Check this if you personally teach this subject. \nGrades will be auto-computed from scores you encode. \nLeave unchecked if another teacher handles this subject \nand you will manually input the final grade.', verbose_name='I am the subject teacher for this')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section')),
            ],
        ),
    ]
