# Generated by Django 6.0.6 on 2026-06-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core'), ('academic_elective', 'Academic Elective - All Other'), ('academic_field', 'Academic Elective - Field/Exposure/Sports/Arts'), ('techpro_elective', 'TechPro Elective - All Other'), ('techpro_immersion', 'TechPro Elective - Work Immersion')], default='core', max_length=20),
        ),
    ]
