# Generated by Django 6.0.6 on 2026-06-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term'),
        ),
    ]
