# Generated by Django 5.1.4 on 2026-06-06 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='term.term'),
            preserve_default=False,
        ),
    ]
