# Generated by Django 5.1.4 on 2026-05-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='role',
            field=models.CharField(choices=[('advisory', 'Adviser'), ('subjectTeacher', 'Subject Teacher')], default='subjectTeacher', max_length=50),
        ),
    ]
