# Generated by Django 5.1.4 on 2026-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='grade_level',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
