# Generated by Django 5.1.4 on 2026-05-31 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolYear', '0002_schoolyear_is_active'),
        ('sections', '0002_section_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='school_year',
            field=models.ForeignKey(default={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='schoolYear.schoolyear'),
        ),
    ]
