# Generated by Django 5.1.4 on 2026-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_section_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_type',
            field=models.CharField(choices=[('JHS', 'Junior High School'), ('SHS', 'Senior High School')], default='JHS', max_length=100, null=True),
        ),
    ]
