# Generated by Django 5.1.4 on 2026-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='order',
            field=models.IntegerField(),
        ),
    ]
