# Generated by Django 5.1.4 on 2026-05-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolYear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active Status'),
        ),
    ]
