# Generated by Django 5.1.4 on 2026-06-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
    ]
