# Generated by Django 6.0.6 on 2026-06-08 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='term.term')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('enrollment', 'date', 'term')},
            },
        ),
    ]
